### ISSUE TITLE
What's the best way to contact you? I have an acquisition Inquiry to make.

### ISSUE THREAD

**Issue by w3guy** [miled/cssviewer#17]
Hi @miled I want to make an acquisition enquiry. How do I contact you?

**Comment by miled** [comment]
@collizo4sky 
Hi. You can contact me on my personal email here https://pastebin.com/raw/N2McWeDU

**Comment by collizo4sky** [comment]
@miled I sent you a mail. Awaiting your response.

**Comment by qoodlechrome** [comment]
Hi @miled can you provide me email?
I want to buy your extension
